import React, { useEffect, useRef, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { multiFactor, TotpMultiFactorGenerator, TotpSecret } from 'firebase/auth';
import { auth } from '../../firebase';

/**
 * One-time TOTP enrollment, shown to the admin when no second factor is enrolled.
 * The shared secret is generated by Firebase and rendered as a QR code + manual key
 * entirely in the browser — it is never sent anywhere by us. After the admin scans
 * it and enters a valid code, the factor is enrolled and every future login requires it.
 *
 * Requires the Firebase project to have Identity Platform + TOTP MFA enabled
 * (Authentication → Sign-in method → Advanced → Multi-factor → TOTP). If it isn't,
 * generateSecret throws and we surface a setup hint.
 */
export default function MfaEnroll({ onEnrolled, onSignOut }: {
  onEnrolled: () => void;
  onSignOut: () => void;
}) {
  const [secret, setSecret] = useState<TotpSecret | null>(null);
  const [otpauthUri, setOtpauthUri] = useState('');
  const [code, setCode] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [setupBlocked, setSetupBlocked] = useState('');
  const started = useRef(false);

  useEffect(() => {
    if (started.current) return; // guard StrictMode double-mount
    started.current = true;
    (async () => {
      try {
        const user = auth.currentUser;
        if (!user) return;
        const session = await multiFactor(user).getSession();
        const s = await TotpMultiFactorGenerator.generateSecret(session);
        setSecret(s);
        setOtpauthUri(s.generateQrCodeUrl(user.email || 'admin', 'Foodyzz Admin'));
      } catch (err: any) {
        // Most likely: TOTP MFA not enabled on the project, or session too old.
        if (err?.code === 'auth/operation-not-allowed' || err?.code === 'auth/admin-restricted-operation') {
          setSetupBlocked('TOTP two-factor auth is not enabled on this Firebase project yet. An owner must enable it in the console (Authentication → Sign-in method → Advanced → Multi-factor → TOTP), then reload.');
        } else if (err?.code === 'auth/requires-recent-login') {
          setSetupBlocked('For security, please sign out and sign back in, then set up 2FA.');
        } else {
          setSetupBlocked(err?.message || 'Could not start 2FA setup. Please reload and try again.');
        }
      }
    })();
  }, []);

  const verify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!secret) return;
    setBusy(true); setError('');
    try {
      const assertion = TotpMultiFactorGenerator.assertionForEnrollment(secret, code.trim());
      await multiFactor(auth.currentUser!).enroll(assertion, 'Authenticator app');
      onEnrolled();
    } catch (err: any) {
      const invalid = err?.code === 'auth/invalid-verification-code' || err?.code === 'auth/missing-code';
      setError(invalid
        ? 'That code was not valid. Wait for the next code in your app and try again.'
        : (err?.message || 'Could not enable 2FA. Please try again.'));
      setBusy(false);
    }
  };

  // Group the manual key into 4-char blocks for readable manual entry.
  const manualKey = secret ? (secret.secretKey.match(/.{1,4}/g) || []).join(' ') : '';

  return (
    <div className="flex items-center justify-center min-h-screen bg-stone-100 p-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-6">
          <img src={`${process.env.PUBLIC_URL}/images/mainpage/splashscreen.png`} alt="Foodyzz" className="h-16 w-auto border-4 border-black shadow-brutalist inline-block mb-4" />
          <h1 className="font-black uppercase tracking-tighter text-2xl">Secure Your Account</h1>
          <p className="text-stone-500 text-xs font-mono uppercase mt-1">Set up two-factor authentication</p>
        </div>

        <div className="bg-white border-4 border-black shadow-brutalist p-6">
          {setupBlocked ? (
            <>
              <p className="text-sm text-stone-700 mb-4">{setupBlocked}</p>
              <button onClick={onSignOut} className="w-full font-black uppercase text-xs text-rose-600 hover:underline py-2">Sign out</button>
            </>
          ) : !secret ? (
            <p className="text-center font-mono text-sm text-stone-500 py-8">Preparing your secure key…</p>
          ) : (
            <>
              <ol className="text-sm text-stone-700 space-y-1 mb-4 list-decimal list-inside">
                <li>Open an authenticator app (Google Authenticator, Authy, 1Password…).</li>
                <li>Scan the QR code, or add the key manually.</li>
                <li>Enter the 6-digit code it shows.</li>
              </ol>

              <div className="flex justify-center my-4">
                <div className="border-4 border-black p-3 bg-white shadow-brutalist">
                  <QRCodeSVG value={otpauthUri} size={168} level="M" />
                </div>
              </div>

              <div className="mb-4">
                <label className="font-black uppercase text-[10px] tracking-widest text-stone-500 block mb-1">Or enter this key manually</label>
                <div className="font-mono text-sm break-all bg-stone-100 border-2 border-black px-3 py-2 select-all">{manualKey}</div>
              </div>

              <form onSubmit={verify} className="space-y-3">
                <div>
                  <label className="font-black uppercase text-[10px] tracking-widest text-stone-500 block mb-1">6-digit code</label>
                  <input
                    type="text"
                    inputMode="numeric"
                    autoComplete="one-time-code"
                    value={code}
                    onChange={e => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
                    required
                    maxLength={6}
                    placeholder="000000"
                    className="w-full border-2 border-black px-3 py-2 font-mono text-lg tracking-[0.4em] text-center focus:outline-none focus:border-brand-green"
                  />
                </div>
                {error && <p className="text-red-500 text-xs font-bold font-mono">{error}</p>}
                <button
                  type="submit"
                  disabled={busy || code.length !== 6}
                  className="w-full bg-black text-white font-black uppercase text-sm py-3 border-2 border-black shadow-brutalist hover:shadow-none hover:translate-x-1 hover:translate-y-1 transition-all disabled:opacity-50"
                >
                  {busy ? 'Enabling…' : 'Enable 2FA →'}
                </button>
              </form>
              <button onClick={onSignOut} className="w-full font-black uppercase text-xs text-stone-500 hover:text-rose-600 py-2 mt-1">Sign out</button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
